core/urls.py
from django.urls import path

from . import views

app_name = "core"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("my_account/", views.my_account_view, name="my_account"),
    path("profile/<slug:username>", views.profile, name="profile"),
    path("potential_matches", views.match_view, name="potential_matches"),
    path("signup/", views.signup_view, name="signup"),
    path("answer_question/<int:question_id>", views.answer_questions, name="answer_question"),
    path("answer_question/", views.answer_random_questions, name="answer_random_question"),
    path("add_question/", views.add_question, name="add_question"),
]

soupunderground/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import include, path

from soupunderground.forms import MyLoginForm

# from django.contrib.auth.urls
urlpatterns = [
    path("", include("core.urls")),
    path("admin/", admin.site.urls),
    path(
        "accounts/login/",
        LoginView.as_view(template_name="registration/login.html", authentication_form=MyLoginForm),
        name="login",
    ),
    path("accounts/logout/", LogoutView.as_view(), name="logout"),
]

core/models.py
from datetime import datetime
from math import acos, cos, pi, sin, sqrt
from random import randint

from django.contrib.auth.models import User
from django.db import models
from django.db.models.aggregates import Count
from django.utils.translation import ugettext_lazy as _


class QuestionManager(models.Manager):
    def random(self):
        """ will select a random row from the database in an efficient way """
        count = self.aggregate(ids=Count("id"))["ids"]
        random_index = randint(0, count - 1)
        return self.all()[random_index]


class Question(models.Model):
    question_text = models.CharField(max_length=500)
    pub_date = models.DateTimeField("date published", auto_now_add=True)
    possible_answers = models.JSONField(default=list)

    def __str__(self):
        return self.question_text

    objects = QuestionManager()


class Answer(models.Model):
    class Meta:
        unique_together = (
            "user",
            "question",
        )

    class Importance(models.IntegerChoices):
        NOT_IMPORTANT = 0, _("doesn't matter at all")
        SLIGHTLY = 1, _("a little")
        MEDIUM = 50, _("average")
        VERY_IMPORTANT = 250, _("very important")
        MANDATORY = 300, _("mandatory")

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer_self = models.CharField(max_length=128, null=True)
    answer_other = models.JSONField(default=list)
    importance = models.IntegerField(choices=Importance.choices, default=50)
    irrelevant = models.BooleanField(default=False)
    hide_my_answer = models.BooleanField(default=False)
    created_at = models.DateTimeField("date answered", auto_now_add=True)
    changed_at = models.DateTimeField("date last updated", auto_now=True)

    def __str__(self):
        return f"{self.user.username}: {self.question.question_text}"


class MatchingCache(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    other_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="other_user")
    forward_score = models.DecimalField(default=0, decimal_places=1, max_digits=5)
    backward_score = models.DecimalField(default=0, decimal_places=1, max_digits=5)
    combined_score = models.DecimalField(default=0, decimal_places=1, max_digits=5)


class Location(models.Model):
    name_of_location = models.CharField(max_length=128, null=False, unique=True)

    longitude = models.FloatField()
    latitude = models.FloatField()

    created_at = models.DateTimeField("date added", auto_now_add=True)
    changed_at = models.DateTimeField("date last updated", auto_now=True)


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    location = models.ForeignKey(Location, null=True, on_delete=models.SET_NULL)
    location_description = models.CharField(max_length=100)
    birthdate = models.DateField(null=True)

    @property
    def age(self):
        return int((datetime.now().date() - self.birthdate).days / 365.25)


class CustomProfileQuestion(models.Model):
    profile_question = models.CharField(max_length=500)
    pub_date = models.DateTimeField("date published", auto_now_add=True)

    def __str__(self):
        return self.profile_question


class CustomProfileAnswer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(CustomProfileQuestion, on_delete=models.CASCADE)
    answer = models.TextField()
    importance = models.IntegerField(default=1)
    created_at = models.DateTimeField("date answered", auto_now_add=True)
    changed_at = models.DateTimeField("date last updated", auto_now=True)

    def __str__(self):
        return f"{self.user.username}: {self.question.profile_question}"


class GeographicCoordinates(object):
    """Geopraphic coordinates represented by latitude (north=positive degrees, south=negative degrees),
    and longitude (west in positive degrees, east in negative degrees)"""

    _earth_radius = (6357 + 6371) / 2  # km

    def __init__(self, latitude: float, longitude: float):
        # calculate coordinates in radians
        to_radians = pi / 180
        self.lat_rad = latitude * to_radians
        self.long_rad = -longitude * to_radians
        self.theta = abs(90 - latitude) * to_radians
        self.phi = -longitude * to_radians

    def __str__(self):
        return f"{str(self.lat_rad)}, {str(self.long_rad)}"

    def direct_distance_in_space(self, other: "GeographicCoordinates") -> float:
        """ calculates the direct distance of two points on this planet, assuming it's a perfect sphere """

        inner = 1 - sin(self.phi) * sin(other.phi) * cos(self.theta - other.theta) - cos(other.theta) * cos(self.theta)
        root = sqrt(2 * inner)
        return self._earth_radius * root

    def great_circle_distance(self, other: "GeographicCoordinates") -> float:
        """ calculates the distance distance along the surface """
        sinus_part = sin(self.lat_rad) * sin(other.lat_rad)
        cosine_part = cos(self.lat_rad) * cos(other.lat_rad) * cos(abs(self.long_rad - other.long_rad))
        return self._earth_radius * acos(sinus_part + cosine_part)


class Ad(models.Model):
    by_user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    changed_at = models.DateTimeField(auto_now=True)

    placed_in_latitude = models.FloatField()
    placed_in_longitude = models.FloatField()

    def get_coordinates(self) -> GeographicCoordinates:
        return GeographicCoordinates(latitude=self.placed_in_latitude, longitude=self.placed_in_longitude)

    def set_coordinates(self, coordinates: GeographicCoordinates):
        self.placed_in_latitude = coordinates.lat_rad
        self.placed_in_longitude = coordinates.long_rad

    visible_distance = models.IntegerField(help_text="Distance in which this ad is visible km")
    visible_time = models.IntegerField(help_text="Time in hours for which this is visible since the last change.")

    self_destruct = models.BooleanField()
    self_destruct_time = models.IntegerField(
        help_text="Self-destruct time in hours until which this ad is picked up py cleaner tasks"
    )

core/views.py
import collections

import markdown
from django.contrib import messages
from django.contrib.auth import authenticate, login, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_list_or_404, get_object_or_404, redirect, render
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from .forms import AddQuestionForm, AnswerForm, DeleteAccountForm, ImportDataForm, RequestDataForm, myUserCreationForm
from .matching import chunk_into_tuple
from .models import Answer, CustomProfileAnswer, MatchingCache, Question, User

# from .matching import update_matches


@login_required
def my_account_view(request):
    def render_with_forms(
        password_form=None, delete_form=None, request_data_form=RequestDataForm(), import_data_form=ImportDataForm()
    ):
        return render(
            request,
            "account.html",
            {
                "user": user,
                "password_form": password_form,
                "delete_form": delete_form,
                "request_data_form": request_data_form,
                "import_data_form": import_data_form,
            },
        )

    user = request.user
    if request.method == "POST":
        # form needs to contain the field password=true if it is about changing the password
        if request.POST.get("password") == "true":
            print("wants to change password")
            password_form = PasswordChangeForm(request.user, request.POST)
            if password_form.is_valid():
                user = password_form.save()
                update_session_auth_hash(request, user)  # Important!
                messages.success(request, "Your password was successfully updated!")
                return redirect(reverse("core:my_account"))
            else:
                return render_with_forms(password_form=password_form, delete_form=DeleteAccountForm())
        # form needs to contain the field delete=true if it is about deleting the account
        elif request.POST.get("delete") == "true":
            delete_form = DeleteAccountForm(request.POST, user=request.user)
            if delete_form.is_valid():
                #  do the deed
                try:
                    username = request.user.username
                    request.user.delete()
                    messages.success(request, f"User {username} was deleted.")
                except Exception as e:
                    messages.error(request, f"Error {str(e)}")
                return redirect(reverse("core:my_account"))
            else:
                messages.warning(request, "please confirm and type your correct password")
                return render_with_forms(PasswordChangeForm(request.POST), delete_form=delete_form)
        else:
            messages.error(request, "unknown form request")
            return redirect(reverse("core:my_account"))
    else:
        return render_with_forms(password_form=PasswordChangeForm(request.user), delete_form=DeleteAccountForm())


class IndexView(LoginRequiredMixin, generic.ListView):
    template_name = "index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")


@login_required
def profile(request, username):
    req_user = User.objects.get(username=username)
    user_self = request.user
    custom_answers = CustomProfileAnswer.objects.filter(user=req_user.id).order_by("importance")
    question_answers = Answer.objects.filter(user=req_user.id)
    html_answers = [
        [custom_answer.question, markdown.markdown(custom_answer.answer, safe_mode=True)]
        for custom_answer in custom_answers
    ]
    return render(
        request,
        "profile.html",
        {
            "req_user": req_user,
            "question_answers": question_answers,
            "html_answers": html_answers,
        },
    )


@login_required
def match_view(request):
    list_of_match_tuples = chunk_into_tuple(
        MatchingCache.objects.filter(user=request.user).filter(forward_score__gte=0).order_by("-forward_score")
    )
    return render(request, "potential_matches.html", {"list_of_match_tuples": list_of_match_tuples})


@login_required
def profile_other(request, username):
    user_id = User.objects.get(username=username)
    answer_list = get_list_or_404(Answer.objects.filter(user=user_id.pk))
    score = get_object_or_404(MatchingCache.objects.filter(user=request.user.pk, other_user=user_id.pk))
    username = username
    return render(request, "profile_other.html", {"answer_list": answer_list, "score": score, "username": username})


def signup_view(request):
    form = myUserCreationForm(request.POST)
    if form.is_valid():
        form.save()
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password1")
        user = authenticate(username=username, password=password)
        login(request, user)
        messages.success(request, "Successfully created new account, welcome!")
        return redirect("core:index")
    return render(request, "signup.html", {"form": form})


@login_required
def answer_questions(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    # Fetch a possible already existing answer for this user
    answer = Answer.objects.filter(user=request.user).filter(question=question).first()
    if answer is not None:
        initial = {
            "answer_self": answer.answer_self,
            "answer_other": answer.answer_other,
            "importance": answer.importance,
            "hide_my_answer": answer.hide_my_answer,
        }
    else:
        initial = None

    # evaluate the request
    if request.method == "POST":
        # someone send us a form \o/
        form = AnswerForm(request.POST, question=question, initial=initial)
        if form.is_valid():
            # okay someone had valid answers let's get going
            if answer is None:
                # this seems to be a very fresh answer for this user, create database entry
                answer = Answer.objects.create(
                    question=question,
                    user=request.user,
                )

            if collections.Counter(form.cleaned_data.get("answer_other")) == collections.Counter(
                question.possible_answers
            ):
                answer.irrelevant = True

            # update all the changed fields
            for field in form.changed_data:
                setattr(answer, field, form.cleaned_data.get(field, None))

            answer.save()
            return redirect(reverse("core:index"))
        else:
            return render(request, "answer_question.html", {"question": question, "form": form})
    else:
        # someone wants a form
        form = AnswerForm(question=question, initial=initial)
        return render(request, "answer_question.html", {"question": question, "form": form})


@login_required
def answer_random_questions(request):
    # evaluate the request
    if request.method == "POST":
        question_id = request.POST.get("question_id")
        question = get_object_or_404(Question, pk=question_id)

        # Fetch a possible already existing answer for this user
        answer = Answer.objects.filter(user=request.user).filter(question=question).first()
        if answer is not None:
            initial = {
                "answer_self": answer.answer_self,
                "answer_other": answer.answer_other,
                "importance": answer.importance,
                "hide_my_answer": answer.hide_my_answer,
            }
        else:
            initial = None

        # someone send us a form \o/
        form = AnswerForm(request.POST, question=question, initial=initial)
        if form.is_valid():
            # okay someone had valid answers let's get going
            if answer is None:
                # this seems to be a very fresh answer for this user, create database entry
                answer = Answer.objects.create(
                    question=question,
                    user=request.user,
                )

            if collections.Counter(form.cleaned_data.get("answer_other")) == collections.Counter(
                question.possible_answers
            ):
                answer.irrelevant = True

            # update all the changed fields
            for field in form.changed_data:
                setattr(answer, field, form.cleaned_data.get(field, None))

            answer.save()
            return redirect(reverse("core:answer_random_question"))
        else:
            return render(request, "answer_random_question.html", {"question": question, "form": form})
    else:
        # request.user wants a random question
        user = request.user
        question = Question.objects.random()
        form = AnswerForm(question=question, initial=None)
        return render(request, "answer_random_question.html", {"question": question, "form": form})


def add_question(request):
    user = request.user
    if request.POST:
        form = AddQuestionForm(request_payload=request.POST)
        if form.is_valid():
            answers = list()
            for answer_form in form.formset:
                if answer_form.is_valid():
                    answers.append(answer_form.cleaned_data.get("answer"))
            if len(answers) > 1: # todo: catch non-valid form
                question = form.cleaned_data.get("question_text")
                Question.objects.create(
                    question_text=question,
                    possible_answers=answers,
                )

core/templates/components/_form_field.html
<div class="field">
    <label class="label">{{ field.label }}</label>
    <div class="control">
        {{ field }}
    </div>
    {% if field.errors %}
        <p class="help is-danger">
            {% for error in field.errors %}
                <span>{{ error }}</span>
            {% endfor %}
        </p>
    {% else %}
        <p class="help"> {{ field.help_text }}</p>
    {% endif %}
</div>

core/templates/components/custom_profile_message.html
<article class="message is-info">
    <div class="message-header">
        <p>{{ question }}</p>
    </div>
    <div class="message-body">
        {{ answer | safe }}
    </div>
</article>

core/templates/components/match_card.html
<div class="card-body">
    <h5 class="card-title">
        {{ match.other_user }}
    </h5>
    <h6 class="card-subtitle mb-2 text-muted">
        {{ match.forward_score }} % match
    </h6>
    <p class="card-text">
        this is where further infos about the user will be displayed
    </p>

    <a class="button is-primary" href="{% url 'core:profile' match.other_user %}">
        open their profile
    </a>
</div>

core/templates/components/navbar.html
{% load fontawesome_5 %}
<nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item brand" href="#">
            Underground Soup
        </a>

        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="our_navbar">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>

    <div id="our_navbar" class="navbar-menu">
        <div class="navbar-start">
            <a class="navbar-item" href="{% url 'core:index' %}">home</a>

            {% if user.is_authenticated %}
                <a class="navbar-item" href="{% url 'core:profile' user.username %}">
                    my profile
                </a>
            {% endif %}


            <a class="navbar-item" href="{% url 'core:potential_matches' %}">
                potential matches
            </a>

            <a class="navbar-item" href="{% url 'core:index' %}"> questions </a>

        </div>

        <div class="navbar-end">
            <div class="navbar-item">
                <div class="buttons">
                    <a class="button is-primary" href="{% url 'core:my_account' %}">
                        <span class="icon is-small">{% fa5_icon 'user' %}</span><span>My account</span>
                    </a>
                    <a class="button is-light" href="{% url 'logout' %}">
                        <span class="icon is-small">{% fa5_icon 'sign-out-alt' %}</span><span>Log out</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</nav>

<script>
    $(document).ready(function () {
        $(".navbar-burger").click(function () {
            $(".navbar-burger").toggleClass("is-active");
            $(".navbar-menu").toggleClass("is-active");
        });
    });
</script>

core/templates/components/question_collapsed_card.html
<div class="block" id="question_{{ answer.question_id }}">
    <div class="card">
        <div class="card-header">
            <p class="card-header-title is-4">{{ answer.question }}</p>

            <a id="update_question_{{ answer.question_id }}"
               class="card-header-icon is-hidden" aria-label="update"
               href="{% url 'core:answer_question' answer.question.id %}">
                                <span class="icon is-small"><i class="fas fa-edit"
                                                               aria-hidden="true"></i>
                                </span></a>

            <a id="control_question_{{ answer.question_id }}" class="card-header-icon"
               aria-label="see question">
                <span class="icon"><i class="fas fa-angle-down" aria-hidden="true"></i></span>
            </a>
        </div>

        <div id="content_question_{{ answer.question_id }}" class="card-content is-hidden">
            <p class="title is-5">
                {% if user.username == req_user.username %}
                    <b>Your answer:</b>
                {% else %}
                    <b>Their answer:</b>
                {% endif %}
            </p>

            <p class="content">{{ answer.answer_self }}</p>
            <p class="title is-5">
                {% if user.username == req_user.username %}
                    <strong>Answers you'll accept:</strong>
                {% else %}
                    <strong>Answers they'll accept:</strong>
                {% endif %}
            </p>
            <ul class="content">
                {% for accepted_choice in answer.answer_other %}
                    <li>{{ accepted_choice }}</li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $("#control_question_{{ answer.question_id }}").on('click', function () {
            $("#content_question_{{ answer.question_id }}").toggleClass("is-hidden");
            $("#update_question_{{ answer.question_id }}").toggleClass("is-hidden");
        });
    });
</script>

core/templates/components/question_form.html
<div class="columns">
    <div class="column">
        {% if form.errors %}
            <ul class="list">
                {% for field in form %}
                    {% for error in field.errors %}
                        <li class="list-item">{{ field.label }}: {{ error|escape }}</li>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <li class="list-item">{{ error|escape }}</li>
                {% endfor %}
            </ul>
        {% endif %}

        <form method="post">
            {% csrf_token %}
            {% include "components/_form_field.html" with field=question_form.answer_self %}

            {% include "components/_form_field.html" with field=question_form.answer_other %}

            {% include "components/_form_field.html" with field=question_form.importance %}

            {% include "components/_form_field.html" with field=question_form.hide_my_answer %}

            {{ question_form.question_id }}

            <div class="field is-grouped">
                <p class="control">
                <div class="buttons">
                    <button type="submit" class="button is-primary">
                        {% if random %}
                            Save and Next
                        {% else %}
                            Save
                        {% endif %}
                    </button>
                    {% if random %}
                        <button class="button is-primary is-outlined"
                                onclick="window.location={% url 'core:answer_random_question' %}">
                            Skip and Next
                        </button>
                    {% endif %}
                </div>
                </p>
            </div>
        </form>
    </div>

    <div class="column">
        <div id="engage_conversation_links" class="box is-hidden">
            <h2 class="subtitle is-3">This seems important to you! Do you want to start a conversation about
                it?</h2>
            <a class="button is-medium is-twitter"
               href="https://twitter.com/intent/tweet?text={{ question.question_text }}
               https://{{ base_url }}{% url 'core:answer_question' question_id=question.id %}">
                <i class="fab fa-twitter fa-lg"></i>
            </a>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        function animate_appearance(object) {
            object.hide();
            object.toggleClass("is-hidden", false);
            object.show(400);
        }

        const conversationLinks = $("#engage_conversation_links");
        const value = $("#id_importance option:selected").val();
        if (value > 200) {
            animate_appearance(conversationLinks);
        }
        $("#id_importance").on('change', (event) => {
            if ($(event.currentTarget).val() > 200) {
                animate_appearance(conversationLinks);
            } else {
                conversationLinks.toggleClass("is-hidden", true);
            }
        })
    });
</script>